sulu/SuluCommunityBundle

- Form/Type/CompletionContactType.php
- Form/Type/ProfileAddressType.php
- Form/Type/ProfileContactAddressType.php
- Form/Type/ProfileContactType.php
- Form/Type/RegistrationContactType.php
| Q | A
| --- | ---
Set the block prefix for same entities to the same value.
This simplifies the form theming so he can style the a specific field e.g. birthday in registration and profile the same way without copying the code.
```twig
{% block contact_row %}
{{- form_label(form) -}}
{{- form_errors(form) -}}
{{- form_widget(form) -}}
{% endblock %}
{% block contact_address_row %}
{{- form_label(form) -}}
{{- form_errors(form) -}}
{{- form_widget(form) -}}
{% endblock %}
{% block address_row %}
{{- form_label(form) -}}
{{- form_errors(form) -}}
{{- form_widget(form) -}}
{% endblock %}
```
When you not set a specific prefix you need to add a block `profile_contact`, `registration_contact`, …
> Add block prefixes to simplify form theming

- Controller/AbstractController.php
| Q | A
| --- | ---
Do not generate a new salt when password is reseted.
Encoder will use the old salt for generate the new password hash.
> Fix password reset when user has salt

- Controller/BlacklistConfirmationController.php
- DependencyInjection/Configuration.php
| Q | A
| --- | ---
- Fix the blacklist configuration to send the registration mail.
- Block blacklist user when deny.
> Fix blacklist email

- EventListener/CompletionListener.php
| Q | A
| --- | ---
Set completion listener redirect header to cache private.
302 Redirects will be cached when public.
> Fix completion listener for not cache 302 redirect

- Tests/Unit/Validator/BlockedValidatorTest.php
- Validator/Constraints/BlockedValidator.php
| Q | A
| --- | ---
| Fixed tickets | fixes #25
Check if one blocked entry exists in validation.
A user can if first entry is just on request.
> Fix registration block after deny over request

- CHANGELOG.md
- EventListener/CompletionListener.php
| Q | A
| --- | ---
Do completion listener redirect only on safe methods.
> Only check completion listener on safe http methods

- CHANGELOG.md
- Controller/ConfirmationController.php
- Tests/app/Resources/webspaces/sulu.io.xml
| Q | A
| --- | ---
| Fixed tickets | fixes #32 
```yml
webspaces:
kuechengoetter:
confirmation:
redirect_to: /{localization}/completion?confirmed=true
webspaces:
kuechengoetter:
confirmation:
redirect_to: route_name
```
> allow route name and add locale replacer in confirmation redirect

- CHANGELOG.md
- Controller/AbstractController.php
| Q | A
| --- | ---
When is choosen by the salt e.g. use md5 when salt not exist the salt need to be set before choose the encoder.
Else it will return a false encoder and the user can not login.
> Fixed get correct encoder for new salt

- CHANGELOG.md
- Tests/Functional/Controller/EmailConfirmationControllerTest.php
| Q | A
| --- | ---
There was an error when the user has no email (fixed by commit https://github.com/sulu/SuluCommunityBundle/commit/7e58a93c25c1efd66c4496397ea2f23698720ee2)
> Added testcase for email-confirmation if user has no email

- Controller/ProfileController.php
- UPGRADE.md
| Q | A
| --- | ---
| BC breaks? | yes
Change fullname to username in media upload.
Privacy!
When uploaded a profile picture the filename will be the username not the fullname now.
> Change profile avatar title from fullname to username

- DependencyInjection/CompilerPass/CommunityManagerCompilerPass.php
- DependencyInjection/CompilerPass/CommunityValidatorCompilerPass.php
- DependencyInjection/Configuration.php
- DependencyInjection/SuluCommunityExtension.php
- EventListener/LastLoginListener.php
- Resources/config/last-login-refresh.xml
- Resources/config/last-login.xml
- UPGRADE.md
| Q | A
| --- | ---
Add posibility to refresh last login every 10 minutes.
> add last login refresh request event listener

- DependencyInjection/CompilerPass/CommunityManagerCompilerPass.php
- DependencyInjection/Configuration.php
- Mail/Mail.php
- Resources/doc/2-setup-webspace.md
- Resources/doc/3-customization.md
- Tests/Unit/Listener/BlacklistListenerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #52 
| Related issues/PRs | -
| Documentation PR | in this PR
This PR makes it possible to also configure the name in the emails sent by the system
So instead of configuring:
```yml
webspaces:
<webspace_name>:
from: test@example.com
to: test@example.com
```
This is also possible (and documented to do it this way):
```yml
webspaces:
<webspace_name>:
from: 
name: Test
email: test@example.com
to: 
name: Test
email: test@example.com
```
It fixes #52 and makes e-mails sent by the system look nicer in the users inbox.
See above
None
-
> Also make name in emailadresses configurable

- Resources/doc/2-setup-webspace.md
| Q | A
| --- | ---
update webspace configuration use exist sulu_admin.email parameter
avoid pitfulls.
```php
webspaces:
<webspace_key>:
from:
name: 'Website'
email: %sulu_admin.email%
```
none
> update webspace configuration use exist sulu_admin.email parameter

- Form/Type/CompletionType.php
- Form/Type/ProfileContactAddressType.php
- Form/Type/RegistrationType.php
- Resources/doc/11-completion.md
- Resources/doc/5-registration.md
- Resources/doc/9-profile.md
| Q | A
| --- | ---
When using this bundle with symfony 3.3 it throws an exception because the sub-types has to be full-qualified-classes.
> Removed class construction for sub-types

- .travis.yml
- Controller/ConfirmationController.php
- Controller/ProfileController.php
- Entity/BlacklistItem.php
- Entity/BlacklistUser.php
- Entity/BlacklistUserRepository.php
- Entity/EmailConfirmationTokenRepository.php
- EventListener/BlacklistListener.php
- EventListener/CompletionListener.php
- EventListener/EmailConfirmationListener.php
- Manager/CommunityManager.php
- Manager/CommunityManagerInterface.php
- Manager/UserManager.php
- Manager/UserManagerInterface.php
- Tests/Functional/Controller/ProfileControllerTest.php
- Tests/Functional/Controller/RegistrationTest.php
- Tests/travis.php.ini
- composer.json
- phpstan.neon
| Q | A
| --- | ---
Add phpstan to travis ci.
To avoid common errors in code.
> Add phpstan to travis ci

- Resources/doc/4-login.md
| Q | A
| --- | ---
| Fixed tickets | fixes #40
Add sulu http cache header configuration to documentation.
Its needed to avoid a that the login-embed shows a cached version in the browser after successfully logout.
> Add documentation for client side cache headers

- .travis.yml
- Command/InitCommand.php
- Controller/AbstractController.php
- Entity/BlacklistUserRepository.php
- Entity/EmailConfirmationTokenRepository.php
- EventListener/EmailConfirmationListener.php
- Manager/CommunityManager.php
- Manager/CommunityManagerInterface.php
- Manager/UserManager.php
- Manager/UserManagerInterface.php
- Tests/Functional/Controller/ProfileControllerTest.php
- composer.json
| Q | A
| --- | ---
| Fixed tickets | fixes #46 
Write also the main email entity when main email address is changed.
Else the content manager has problems when editing community contacts.
Added a function to the `updateUser` to `UserManagerInterface`.
> Create and update correct email entity for backend edit

- Manager/CommunityManager.php
| Q | A
| --- | ---
| Fixed tickets | fixes #28
Enable the user on password reset.
When a user did forgot to confirm his email address this is currently. He can currently send himself a password reset email. That he can correctly use the system we need to enable him as with the password reset email he did also confirm his identity.
> confirm and enable user also with password reset email

- .github/ISSUE_TEMPLATE.md
| Q | A
| --- | ---
Add bundle version to github issue template.
To get the sulu version and the bundle version for issues.
> Add bundle version to github template

- .github/PULL_REQUEST_TEMPLATE.md
- .styleci.yml
- Controller/LoginController.php
- DependencyInjection/CompilerPass/CommunityManagerCompilerPass.php
- DependencyInjection/Configuration.php
- Resources/doc/13-maintenance.md
- Resources/doc/3-customization.md
- Resources/views/Login/login-embed.html.twig
- Resources/views/Maintenance/maintenance.html.twig
| Q | A
| --- | ---
It adds a maintenance flag and template to the community bundle which can be enabled and used instead of the other templates.
Sometimes you want temporarily disable community action e.g. Database migrations.
See documentation.
> Add maintenance mode

- DependencyInjection/CompilerPass/CommunityManagerCompilerPass.php
- Resources/doc/3-customization.md
| Q | A
| --- | ---
Fallback to email address to from email address.
To avoid errors as to is not required to be set.
~~~php
webspaces:
<webspace_key>:
from: "%from_email%"
~~~
> Fallback to email address to from email address when not set

- DependencyInjection/Configuration.php
| Q | A
| --- | ---
Symfony seems to normalize keys and replace `-` with `_`. https://symfony.com/doc/current/components/config/definition.html#normalization
Use normalizeKeys function (https://symfony.com/doc/current/components/config/definition.html) to disable this behaviour.
```php
webspace:
test-intranet:
from: test@example.org
```
> Allow webspaces with dash

- Resources/doc/2-setup-webspace.md
| Q | A
| --- | ---
Use route name instead of path in security configuration
To avoid problems when have language specific urls for login
> Use route name instead of path in security configuration

- .travis.yml
- Resources/views/Login/login-embed.html.twig
- Tests/travis.php.ini
| Q | A
| --- | ---
Fix twig error in login embed file.
Not valid twig file.
> Fix login embed example file

- .travis.yml
- Admin/CommunityAdmin.php
- Command/InitCommand.php
- Controller/AbstractController.php
- DependencyInjection/CompilerPass/CommunityManagerCompilerPass.php
- DependencyInjection/CompilerPass/Normalizer.php
- Resources/config/routing_website.xml
- Tests/Functional/Controller/RegistrationTest.php
- Tests/Unit/Listener/BlacklistListenerTest.php
- Tests/app/Resources/webspaces/sulu.io.xml
- Tests/app/config/config_admin.yml
- Tests/app/config/config_website.yml
- Tests/app/config/config_website_prod.yml
| Q | A
| --- | ---
| Fixed tickets | fixes #83
Fix login embed and validate webspace in community admin.
Twig error on development for login embed. Validate if configured community webspace exist.
> Fix false firewall name and validate webspace in community admin

- Resources/doc/1-installation.md
- Resources/doc/index.md
| Q | A
| --- | ---
Add missing documentation for asset install and generate translations
For installation the assets:install and sulu:translate:export need to be called.
> Add missing documentation for asset install and generate translations

- Resources/doc/1-installation.md
| Q | A
| --- | ---
Improve documentation with a better hint for duplicated bundle registration.
Code blocks are less ignored by developers when reading the documentation.
> Improve documentation with a better hint for duplicated bundle registration

- .travis.yml
- Controller/LoginController.php
- DependencyInjection/SuluCommunityExtension.php
- Resources/config/doctrine/BlacklistItem.orm.xml
- Resources/config/doctrine/BlacklistUser.orm.xml
- Resources/config/doctrine/EmailConfirmationToken.orm.xml
- Tests/app/config/config_admin.yml
- Tests/app/config/config_website.yml
- UPGRADE.md
- composer.json
| Q | A
| --- | ---
Fix compatibility with jms serializer.
Following error does appear on sulu 2.0:
> The attribute "name" must be set for path "jms_serializer.metadata.directories"
> Fix compatibility with jms serializer 2, sulu 2 and mysql utf8mb4

- Controller/CompletionController.php
- Controller/ProfileController.php
- Controller/RegistrationController.php
- Controller/SaveMediaTrait.php
- Tests/Unit/Controller/SaveMediaTraitTest.php
- Tests/app/AppKernel.php
| Q | A
| --- | ---
| Related PRs | https://github.com/sulu/sulu/pull/4092
Added contact documents upload and fixed profile without avatar.
Sometimes you want to allow that a community user can upload files to its contact.
~~~php
$builder->add(
'medias',
FileType::class,
[
'label' => 'attendance_confirmation',
'mapped' => false,
'required' => false,
'multiple' => true,
]
);
~~~
Did keep the saveAvatar function to avoid any bc breaks.
> Added contact documents upload and fixed profile without avatar

- Controller/ProfileController.php
- Tests/Functional/Controller/ProfileControllerTest.php
| Q | A
| --- | ---
Fix profile without a note value.
Currently it will throw an insert error on mysql 5.7 when a profile without a note is submitted.
> Fix profile without note for mysql 5.7

- Command/InitCommand.php
- Controller/AbstractController.php
- DependencyInjection/CompilerPass/CommunityManagerCompilerPass.php
- Manager/CommunityManagerRegistry.php
- Manager/CommunityManagerRegistryInterface.php
- Resources/config/services.xml
- Tests/Unit/Manager/CommunityManagerRegistryTest.php
| Q | A
| --- | ---
| Related issues/PRs | non
This PR introduces a registry for the community-managers (webspace specific).
This replaces the handling of ids inside of the controller or other extensions.
> Added registry for community-manager

- .travis.yml
- composer.json
| Q | A
| --- | ---
Fix composer deprecation and upgrade ci to php 7.3
> Deprecation warning: require.beberlei/DoctrineExtensions is invalid, it should not contain uppercase characters. Please use beberlei/doctrineextensions instead. Make sure you fix this as Composer 2.0 will error
And to test community bundle on php 73
> Fix composer deprecation and upgrade ci to php 7.3

- Command/InitCommand.php
| Q | A
| --- | ---
This PR adjusts the `InitCommand` to call flush on the `EntityManager` after initializing a webspace.
Because this way it is possible to configure the same role for multiple Webspaces. Otherwise the created role is not flushed and therefore created again during the initialization of the second Webspace. This leads to a `Doctrine\DBAL\Exception\UniqueConstraintViolationException`.
> Fix initializing of webspaces with same role name

- DependencyInjection/Configuration.php
| Q | A
| --- | ---
| Fixed tickets | fixes none
This PR set `useAttributeAsKey` to allow splitting the webspaces config.
If you split the config for webspaces into multiple files.
> Add 'useAttributeAsKey' to webspaces config node
