sulu/SuluCommunityBundle

- Admin/CommunityAdmin.php
- Gruntfile.js
- Resources/config/services.xml
- Resources/public/dist/main.js
- Resources/public/js/main.js
- package.json
| Q | A
| --- | ---
This PR integrates the community into sulu-admin
> Init admin and javascript files

- Build/CommunityBuilder.php
- Command/InitCommand.php
- DependencyInjection/SuluCommunityExtension.php
- Resources/config/services.xml
| Q | A
| --- | ---
This PR adds the community in build-process.
> Added builder to init community-bundle

- .gitignore
- .travis.yml
- Tests/Functional/Controller/LoginControllerTest.php
- Tests/app/AppKernel.php
- Tests/app/Resources/views/master.html.twig
- Tests/app/Resources/webspaces/sulu.io.xml
- Tests/app/config/config_admin.yml
- Tests/app/config/config_website.yml
- Tests/app/config/routing_website.yml
- Tests/app/console
- Tests/bootstrap.php
- composer.json
- phpunit.xml.dist
| Q | A
| --- | ---
This PR bootstrap the functional tests.
> Bootstraped functional testcases

- Command/InitCommand.php
- Controller/AbstractController.php
- Controller/ConfirmationController.php
- Controller/PasswordController.php
- Controller/RegistrationController.php
- Event/CommunityEvent.php
- Manager/CommunityManager.php
- Manager/CommunityManagerInterface.php
- Manager/UserManager.php
- Manager/UserManagerInterface.php
- Resources/config/services.xml
- Validator/Constraints/ExistValidator.php
| Q | A
| --- | ---
Extract user handling from community manager into a user manager service
> Create user manager service

- Controller/AbstractController.php
- DependencyInjection/Configuration.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3
Use the template attributes service.
> Use sulu template attributes service

- Form/Type/ProfileNoteType.php
| Q | A
| --- | ---
Set a block prefix for notes for easier theming
> Set a block prefix for notes for easier theming

- Controller/CompletionController.php
- DependencyInjection/CompilerPass/CommunityValidatorCompilerPass.php
- EventListener/CompletionListener.php
- Resources/config/services.xml
| Q | A
| --- | ---
Fix problems with redirect to fragments.
Because its a bug.
> Fix completion redirect for prod with fragments

- Controller/BlacklistConfirmationController.php
| Q | A
| --- | ---
Remove contact in blacklist request deny.
Else only a user is removed.
> remove contact when user is denied

- Form/Type/CompletionContactType.php
- Form/Type/ProfileContactType.php
- Form/Type/RegistrationContactType.php
- Resources/config/validation.xml
- Tests/Functional/Controller/ProfileControllerTest.php
| Q | A
| --- | ---
| BC breaks? | yes
Fix the validation for sub forms.
Currently subform fields like firstName and lastName are not validated.
> Fix validation for user subentity forms

- CHANGELOG.md
- Form/Type/ProfileAddressType.php
| Q | A
| --- | ---
Translates the country names.
> Translate countries to correct language

- CHANGELOG.md
- composer.json
| Q | A
| --- | ---
Allow that the basic installation is Sulu 1.3.
> Support sulu 1.3 version

- DependencyInjection/Configuration.php
- DependencyInjection/SuluCommunityExtension.php
- README.md
- Resources/config/services.xml
- Resources/doc/1-installation.md
- Resources/doc/10-email-confirmation.md
- Resources/doc/11-completion.md
- Resources/doc/12-blacklisting.md
- Resources/doc/2-setup-webspace.md
- Resources/doc/3-customization.md
- Resources/doc/4-login.md
- Resources/doc/5-registration.md
- Resources/doc/6-confirmation.md
- Resources/doc/7-password-forget.md
- Resources/doc/8-password-reset.md
- Resources/doc/9-profile.md
- Resources/doc/index.md
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Fixed tickets | fixes #34 |
| License | MIT |
https://github.com/sulu/SuluCommunityBundle/tree/feature/doc
> Add documentation

- Tests/Functional/Controller/RegistrationTest.php
| Q | A
| --- | ---
This PR tries to fix the failing testcases.
> Replaced queries to find user

- Resources/doc/3-customization.md
| Q | A
| --- | ---
Documentation for the last login refresh interval.
Its missing.
> added documentation for last login refresh rate

- Form/Type/ProfileAddressType.php
- Form/Type/ProfileContactAddressType.php
- Form/Type/RegistrationType.php
- Resources/config/validation.xml
| Q | A
| --- | ---
Added missing validatons.
Currently there are some constraints missing.
> Added missing default validation constraints

- DependencyInjection/CompilerPass/CommunityManagerCompilerPass.php
- DependencyInjection/CompilerPass/CommunityValidatorCompilerPass.php
- DependencyInjection/Configuration.php
- DependencyInjection/SuluCommunityExtension.php
- EventListener/LastLoginListener.php
- Form/Type/ProfileAddressType.php
- Form/Type/ProfileContactAddressType.php
- Form/Type/RegistrationType.php
- Mail/Mail.php
- Resources/config/last-login.xml
- Resources/config/validation.xml
- Resources/doc/2-setup-webspace.md
- Resources/doc/3-customization.md
- Tests/Unit/Listener/BlacklistListenerTest.php
- UPGRADE.md
[Full Changelog](https://github.com/sulu/SuluCommunityBundle/compare/0.2.0...0.3.0)
**Closed issues:**
- Implement from and to name for emails [\#52](https://github.com/sulu/SuluCommunityBundle/issues/52)
**Merged pull requests:**
- Added missing default validation constraints [\#58](https://github.com/sulu/SuluCommunityBundle/pull/58) ([alexander-schranz](https://github.com/alexander-schranz))
- added documentation for last login refresh rate [\#56](https://github.com/sulu/SuluCommunityBundle/pull/56) ([alexander-schranz](https://github.com/alexander-schranz))
- add last login refresh request event listener [\#55](https://github.com/sulu/SuluCommunityBundle/pull/55) ([alexander-schranz](https://github.com/alexander-schranz))
- Also make name in emailadresses configurable …
> Release 0.3.0

- Resources/doc/2-setup-webspace.md
| Q | A
| --- | ---
Fixed not working documentation.
Because it dont work currently.
> fix documentation for login and logout config

- Resources/doc/5-registration.md
- Resources/doc/9-profile.md
| Q | A
| --- | ---
| Fixed tickets | N/A
| Related issues/PRs | N/A
A minor doc typo.
> Fix minor registration doc typo

- .travis.yml
- Controller/AbstractController.php
- Controller/BlacklistItemController.php
- Controller/ConfirmationController.php
- Controller/EmailConfirmationController.php
- DependencyInjection/CompilerPass/CommunityManagerCompilerPass.php
- EventListener/BlacklistListener.php
- EventListener/CompletionListener.php
- Form/Type/ProfileNoteType.php
- Manager/CommunityManager.php
- Manager/UserManager.php
- Tests/Unit/Listener/BlacklistListenerTest.php
- Tests/Unit/Listener/EmailConfirmationListenerTest.php
- Tests/Unit/Mail/MailFactoryTest.php
- Tests/travis.php.ini
| Q | A
| --- | ---
Fix styleci and php5.5 tests.
Failing because of memory limit.
> Increase memory limit for tests and use yoda conditions for styleci changes

- Form/Type/ProfileContactType.php
- Resources/doc/1-installation.md
- Resources/doc/2-setup-webspace.md
- Resources/doc/3-customization.md
- composer.json
| Q | A
| --- | ---
Run tests with symfony 3.
To run tests in symfony 3 env.
> Run tests with symfony 3

- Resources/doc/4-login.md
| Q | A
| --- | ---
Update documentation.
http://docs.sulu.io/en/latest/cookbook/use-request-analyzer-with-esi.html
> Update documentation for esi preview error

- Admin/CommunityAdmin.php
- DependencyInjection/CompilerPass/CommunityManagerCompilerPass.php
- Resources/config/services.xml
| Q | A
| --- | ---
| Fixed tickets | fixes #60
Add system roles to sulu security.
To show the correct system in user roles edit.
> Fix shown systems in sulu role backend ui

- Resources/doc/3-customization.md
| Q | A
| --- | ---
| Fixed tickets | fixes #issuenum
| Related issues/PRs | #issuenum
Add description to customization documentation
Improve the documentation.
> Add description to customization documentation

- Resources/doc/2-setup-webspace.md
| Q | A
| --- | ---
Document allowing fragment and login in security.yml
Avoid pitfalls.
> Document to allow fragments and login be accessable anonymously

- Resources/doc/2-setup-webspace.md
| Q | A
| --- | ---
Improve webspace configuration documentation by add a hint to replace <webspace_key> correctly.
Avoid copy & paste errors.
> Improve webspace configuration documentation

- Resources/doc/2-setup-webspace.md
| Q | A
| --- | ---
Add test configuration to installation guide.
Needed when you run functional tests in your sulu installation.
> Add test configuration to installation guide

- Manager/UserManager.php
| Q | A
| --- | ---
| Related issues/PRs | sulu/sulu#3942
This PR fixes the use of ContactRepositoryInterface
> Fixed use of moved contact-repository-interface

- Resources/doc/2-setup-webspace.md
| Q | A
| --- | ---
Add allow access of registration, password reset and password forget in example firewall.
To make sure that if somebody secure all he need to allow other public routes.
> Add allow access of registration, password reset and password forget in example firewall

- .travis.yml
- Tests/Unit/Entity/BlacklistItemTest.php
- Tests/Unit/Listener/BlacklistListenerTest.php
- Tests/Unit/Listener/EmailConfirmationListenerTest.php
- Tests/Unit/Mail/MailFactoryTest.php
- Tests/Unit/Manager/BlacklistItemManagerTest.php
- Tests/Unit/Validator/BlockedValidatorTest.php
- Tests/app/AppKernel.php
- composer.json
- phpstan.neon
| Q | A
| --- | ---
| Related Issues/PRs | https://github.com/sulu/sulu/pull/4029
Set minimum stability to dev and add branch alias for 2.0.
To test dev version 2.0 sulu and other bundles.
~~~bash
composer update
~~~
```bash
composer require sulu/community-bundle:^2.0@dev
```
> Fix test cases with sulu 2.0, update to phpunit 6 and add branch alias
